### ISSUE TITLE
End of Report (section) - reports incorrect information.

### ISSUE THREAD

**Issue by CaptainMidnight** [kencormack/system_info#3]
After running a simple report - 'end of report' section appears incorrect and advises: -

==================================================
 TIME REQUIRED TO GENERATE THIS REPORT:  5 minutes and 51 seconds.
==================================================

The following Menu Options were selected, to generate this report:
 **Option 16: Run All Sections**

These menu selections have been saved in the file:
  /home/pi/.system_inforc

They will be auto-selected the next time this script is run.

==================================================
 REPORT SAVED AS:  /home/pi/pi-dev-system_info-2020-06-24-11-30-51
==================================================

There's some issues with this info: -

1. Only section 1 was selected and the report was generated in less than 5sec not 5min 51sec
2. Report name is a bit wrong - also stored in two different locations .i.e current run folder and /root/ and /home/pi/system_info
3. Report in /root is named correctly as phoenix-pi-x64-system_info-2020-06-24-20-08-24

**Comment by CaptainMidnight** [comment]
For reference, test system RPi4B8 PiOS 64bit

**Comment by CaptainMidnight** [comment]
...... on 2nd run 'End of Report' section is correct: -

===============================================================================
 TIME REQUIRED TO GENERATE THIS REPORT:  0 minutes and 0 seconds.
===============================================================================

The following Menu Options were selected, to generate this report:
 Option  1: Pi Hardware

These menu selections have been saved in the file:
  /root/.system_inforc

They will be auto-selected the next time this script is run.

===============================================================================
 REPORT SAVED AS:  /root/phoenix-pi-x64-system_info-2020-06-24-20-31-14
===============================================================================

**Comment by CaptainMidnight** [comment]
Tested again and ran as the standard user account 'pi' everything is OK

**Comment by kencormack** [comment]
Glad to hear it.

A few points I had started to draft before your most recent post...

I'd ask that you not use Huge Fonts to highlight an issue.  It causes lines to wrap on here, and makes it more difficult to read.  Also, describing multiple problems in the same thread makes it difficult for me to respond to each problem individually.  Your first report alone describes no less than three separate problems.

From your report #1...
The first report states in the summary that the report took 5 minutes 51secs to run.  You say you only selected option one, but the report states option 15 was selected.  An execution time of 5:51 is consistent with the times I see when option 15 is selected.  Is it possible you inadvertently had 15 also selected, when you selected option 1?  If both option 1 and option 15 had been selected, the "15" would have overruled the "1", and all tests would run.  Since you were running multiple tests, under multiple accounts (pi and with sudo), is it possible you are misinterpreting which reports were run by which accounts, with which options selected?

As for the report being stored in multiple places... you list three locations:  "current run folder and /root/ and /home/pi/system_info"

The report gets written to the homedir of the userid that runs the script.
If you are "pi" when you run it, the report ends up in /home/pi.
If you run it with sudo, sudo makes you "root", which means the report will get written to root's homedir (/root).
The report never gets written to "current run folder" (unless you happen to be in the user's homedir, or root's homedir, when you run it.  If you "cd /tmp", making /tmp your "current run dir", the report would never end up there.  The redsults are never written to a "system_info" subdirectory (as in the /home/pi/system_info example you gave).

As for the reportname containing an incorrect hostname when trun as the user, but the correct name when run as root, and for any other issues at present.... let me please call your attention to the following statement in 21 June 2020 NOTE in the README.md file for this script....

**NOTE: 21 June 2020
...
I will not be testing the new 64-bit "Raspberry Pi OS" until it comes out of beta, as I prefer not to
chase a moving target, especially this early in it's development.
...
For more details see: https://www.raspberrypi.org/forums/viewtopic.php?t=275370**

As you are running "RPi4B8 PiOS 64bit" (which is specifically the beta release I caution against as untested), I can only guess at why the "hostname" command might return one result to a generic user, and another different result to root.

I suggest you try deleting any existing copies of the reports, (in /root and /home/pi), and then as user pi, run the script again, and only once.  Be careful to note which options you select.  Carefully examine that single report.  If any problems are noted, please email me the following as attachments (my email address is in the comments at the top of the script)...

1.) The contents of /home/pi/.system_inforc
2.) The full contents of the report

As for a "silly user check", that is done on the very first screen, where the title screen notes "running as user:"

Ken

**Comment by kencormack** [comment]
For now, as the script ran as expected when you ran it as "pi", and as it's still so early in the beta development of the 64-bit PiOS (which has otherwise been untested, and wont be for some time), I'll close this issue for now.

**Comment by CaptainMidnight** [comment]
That's fine, as for the issue post formats - that was a result of a cut&past from the ssh client directly into the write field - I'll check this in future thanks.

**Comment by kencormack** [comment]
No worries.
