### ISSUE TITLE
Feedback on my recent run :-)

### ISSUE THREAD

**Issue by bsimmo** [kencormack/system_info#5]
Up to date 
Pi3B+/Buster/5.10 kernel* , Raspberry Pi OS 3.6 
(*which came out a couple of days ago)
Various things installed on system for playing

- Installed as per instructions 
- Needed to installed _lshw_ as expected.
- 14 out of 40 supplemental to be used (no idea which)
- Going ok.
- Error at top of menu system : feedback
```
./system_info.v2.1.2-stretch: line 6177: ./system_info.v3.1.0: syntax error: operand expected (error token is "./system_info.v3.1.0")
RASPBERRY PI SYSTEM INFORMATION REPORT v2.1.2 - MAIN MENU
```

run all of the above :-) 

loads of text flies by in the terminal windows (I'm the desktop :-))

log file https://drive.google.com/file/d/1CJCQA6IzTIt5R68ZTPD8RhjlBG_aBy4e/view?usp=sharing

Is there a built in script to install the other 'tools' that may be needed?
Or any in particular you want testing?

**Comment by kencormack** [comment]
Hello, Ben.
I see by the output of the report you linked to, that you ran the older 2.1.2 version of the script.  Since you are running Buster, please try running the 3.1.0 version, instead.
Not sure what that syntax error was.  I'm not sure if I'm looking at one line of error message (that mentions both versions of the script?) or what.

Please "cd" into the directory into which you downloaded system_info, and run the following command...
    ./system_info.v3.1.0  --menu 17  3> $(hostname).debug.log  4> $(hostname).profile.log 
That command will run the latest version (3.1.0).  It will generate a full report, and two additional files.. a debugging log, and a profiling log.  The former helps me track down any problems, and the latter just helps me spot whether something is taking an abnormally long time to run.

There is no builtin-in mechanism to automatically install any needed tools.  I thought about that long and hard when I first released the script to the public.  I didn't ever want the script blamed for any problems a system might have, and I figured there's going to be *one* person out there somewhere, who would blame my script for a problem "because the script installed some package."  By laying the responsibility for properly installing and managing software packages on the user, any package problems would be user-induced, and not something the script could be blamed for.  It was a difficult choice to make, but I decided to take the "this script makes no changes" position.  Sinc I tell the user what packages are required, and spell out how to install them, I think that's a fair enough compromise.

As for any supplemental packages... one of the things the script can report on is the presence and configuration of a printer.  If a user dose not have a printer, it's not likely that would have the "cups" print engine installed.  It would be pointless to require (or even suggest) that a user install and configure "cups", just so that I could tell them "you don't have any printers defined."  The supplemental tests are simply "Oh, I see you have subsystem-whatever installed... let me see what I can tell you about it."  Installing a supplemental package, when there is no need, isn't helpful to the user, and adds no value to the output from system_info.

As for not knowing which packages the script found, the 3.1.0 version of the script will show you which of the supplemental packages were actually found to be installed.  That was added a few versions ago, and will appear at the top of the report.

And yeah, a lot of text flies by, on the screen... but it all gets captured in the report file, so none of it is lost.

Ken

    On Sunday, February 7, 2021, 7:10:28 AM EST, Ben <notifications@github.com> wrote:  
 
 


Up to date
Pi3B+/Buster/5.10 kernel* , Raspberry Pi OS 3.6
(*which came out a couple of days ago)
Various things installed on system for playing
   
   - Installed as per instructions
   - Needed to installed lshw as expected.
   - 14 out of 40 supplemental to be used (no idea which)
   - Going ok.
   - Error at top of menu system : feedback
./system_info.v2.1.2-stretch: line 6177: ./system_info.v3.1.0: syntax error: operand expected (error token is "./system_info.v3.1.0")
RASPBERRY PI SYSTEM INFORMATION REPORT v2.1.2 - MAIN MENU

run all of the above :-)

loads of text flies by in the terminal windows (I'm the desktop :-))

log file https://drive.google.com/file/d/1CJCQA6IzTIt5R68ZTPD8RhjlBG_aBy4e/view?usp=sharing

Is there a built in script to install the other 'tools' that may be needed?
Or any in particular you want testing?

**Comment by bsimmo** [comment]
When I ran it, I just followed your instruction on the front and that's the error I saw.

i.e.
```
$ git clone https://github.com/kencormack/system_info.git
$ cd system_info
$ chmod +x system_info*
$ ./system_info*
```
Perhaps it's just showing an error trying to run the stretch version, before the current version. 
I understand the reasoning, just a pain to build up an add list. 
I'll not bother as I don't use them or know why extra they provide. (I'm just playing :-)) 

Printing (Cups and other things iirc.) is installed by default now, it was added to the images (I'm not sure I 'lite' has it installed though, perhaps just the desktop)

I had a look through the list but only a scan.
I can see when I updated kernels, and rebooted which is nice.

**Comment by kencormack** [comment]
Ah, I see my use of a wildcard in the instructions, is causing the confusion.  I can also see how it would generate the error you saw.  I'll have to clarify that, in the README, to state that the user run only the appropriate version (or delete the unneeded version), or whatever.  Is just wanted to avoid having to re-edit the README every time there's a version change, to keep updating the step such as..../system_info.v3.0.0...
./system_info.v3.0.1..../system_info.v3.0.2...
./system_info.v3.0.3...
...ad nauseum
I'll figure out how I want to word that, and will get that in with the next push.

In the meantime, you can always just delete the stretch version each time you do a "git pull".  As most folks should be on Buster, I will, at some point, get rid of the Stretch version from the github repository, I suppose.  But in the meantime, I want to keep it there because not everyone will have upgraded their legacy systems to Buster.

Also, I've added the call to the agnostics speed test to the script, and am running a test now, on all my machines.  :)

Ken


    On Sunday, February 7, 2021, 10:05:01 AM EST, Ben <notifications@github.com> wrote:  
 
 


When I ran it, I just followed your instruction on the front and that's the error I saw.

i.e.
$ git clone https://github.com/kencormack/system_info.git
$ cd system_info
$ chmod +x system_info*
$ ./system_info*

Perhaps it's just showing an error trying to run the stretch version, before the current version.
I understand the reasoning, just a pain to build up an add list.
I'll not bother as I don't use them or know why extra they provide. (I'm just playing :-))

Printing (Cups and other things iirc.) is installed by default now, it was added to the images (I'm not sure I 'lite' has it installed though, perhaps just the desktop)

I had a look through the list but only a scan.
I can see when I updated kernels, and rebooted which is nice.

**Comment by kencormack** [comment]
Test was successful.  This'll go in the next update to the script...

===============================================================================
SYSTEM_INFO(2): AGNOSTICS MEDIA SPEED TEST
===============================================================================

Run 1
prepare-file;0;0;76204;148
seq-write;0;0;78486;153
rand-4k-write;0;0;63689;15922
rand-4k-read;44311;11077;0;0
Sequential write speed 78486 KB/sec (target 10000) - PASS
Random write speed 15922 IOPS (target 500) - PASS
Random read speed 11077 IOPS (target 1500) - PASS
Ken

    On Sunday, February 7, 2021, 10:05:01 AM EST, Ben <notifications@github.com> wrote:  
 
 


When I ran it, I just followed your instruction on the front and that's the error I saw.

i.e.
$ git clone https://github.com/kencormack/system_info.git
$ cd system_info
$ chmod +x system_info*
$ ./system_info*

Perhaps it's just showing an error trying to run the stretch version, before the current version.
I understand the reasoning, just a pain to build up an add list.
I'll not bother as I don't use them or know why extra they provide. (I'm just playing :-))

Printing (Cups and other things iirc.) is installed by default now, it was added to the images (I'm not sure I 'lite' has it installed though, perhaps just the desktop)

I had a look through the list but only a scan.
I can see when I updated kernels, and rebooted which is nice.

**Comment by bsimmo** [comment]
add a prefix and call it stretch_system_info...
that way the wildcard will still work.

Maybe v3 could check for Buster (or some such OS version check) and stop running and recommend the old version?
That could then be used in future versions as OS's are dropped.
Anyway, easy enough for now :-)

**Comment by kencormack** [comment]
Renaming the stretch version has already struck me as the simplest way to go, short of dropping it all together.

As for version checks, the script already checks to ensure it's running on the supported version(s) of the O/S.  For example, the 3.x version will complain if it's launched on Stretch.  It just doesn't say anything suggesting that another version be used.  Doing so would almost obligate me to keep future obsolete/EOL versions around forever.
Ken

    On Sunday, February 7, 2021, 1:01:34 PM EST, Ben <notifications@github.com> wrote:  
 
 


add a prefix and call it stretch_system_info...
that way the wildcard will still work.

Maybe v3 could check for Buster (or some such OS version check) and stop running and recommend the old version?
That could then be used in future versions as OS's are dropped.
Anyway, easy enough for now :-)

**Comment by kencormack** [comment]
Old version has been renamed, and instructions clarified in the README.md
