### ISSUE TITLE
Suggestion : Consider using "agnostics"

### ISSUE THREAD

**Issue by bsimmo** [kencormack/system_info#6]
Consider using **agnostics** for the drive benchmarks

_agnostics_ is the "build in" RasperryPiOS benchmark for the drive.

Implemented on the command line with
```
cd /usr/share/agnostics
sh agnostics
```
or just
`/bin/sh /usr/share/agnostics/sdtest.sh`

and provides output like
```
Run 1
prepare-file;0;0;16062;31
seq-write;0;0;11603;22
rand-4k-write;0;0;3291;822
rand-4k-read;8451;2112;0;0
Sequential write speed 11603 KB/sec (target 10000) - PASS
Random write speed 822 IOPS (target 500) - PASS
Random read speed 2112 IOPS (target 1500) - PASS
```
it repeats the test until it passes all three, or after the third attempt.

https://github.com/raspberrypi-ui/agnostics

**Comment by kencormack** [comment]
Hi again -
This is a good suggestion.  I don't really consider agnostic to be a "great" speed test, since it doesn't really exercise the storage device the way other benchmark tools do, but it DOES give a nice quick look at potential throughput, without putting undo wear and tear on wear-sensitive media.

Thank you for the solid suggestion.  I'll add it later today, and it'll show up in the next release.
Ken


    On Sunday, February 7, 2021, 7:29:45 AM EST, Ben <notifications@github.com> wrote:  
 
 


Consider using agnostics for the drive benchmarks

agnostics is the "build in" RasperryPiOS benchmark for the drive.

Implemented on the command line with
cd /usr/share/agnostics
sh agnostics

or just
/bin/sh /usr/share/agnostics/sdtest.sh

and provides output like
Run 1
prepare-file;0;0;16062;31
seq-write;0;0;11603;22
rand-4k-write;0;0;3291;822
rand-4k-read;8451;2112;0;0
Sequential write speed 11603 KB/sec (target 10000) - PASS
Random write speed 822 IOPS (target 500) - PASS
Random read speed 2112 IOPS (target 1500) - PASS

it repeats the test until it passes all three, or after the third attempt.

https://github.com/raspberrypi-ui/agnostics

**Comment by kencormack** [comment]
Agnostics has been added.  Thanks for the suggestion.
